.gitignore, package.json, yarn.lock
*The solution currently relies on serialize-javascript version < 2.1.1. This version is vulnerable to XSS attacks. Upgrading the dependency to version 2.1.1 *
=> Adding serialize-javascript

source/lambda/helper/python/comprehendHelper.py
Bug Fix:
For Comprehend Medical ICD10 CM, DUS was calling detect_entities_V2 API where the call had to be made to infer_icd10_cm API
Fixed the API call in this PR
=> BugFix: Fixing API call made for ICD10-CM ontologies in Comprehend Medical

source/lib/cdk-textract-stack.ts
…ment and samples buckets for indexing
kendra is unable to index uploaded documents from users and samples because its role doesn't have permission to those bucket 
Kendra's role is given permission to access documents and samples buckets 
=> fixed kendra permission issue to access documents and samples

source/app/components/Button/Button.js, source/app/components/DocumentPreview/DocumentPreview.js, source/app/components/TableDownloader/TableDownloader.js, source/app/pages/_app.js, source/package-lock.json, source/package.json, source/yarn.lock
*Issue #, if available:* Relates to #30
* Updated version of next.js to 9.4.4
* Removed the `<Container>` wrapper in _app.js since it's now redundant
* Removed some now-unnecessary module resolution rules that broke in 9.0
* Rearranged the various options available to `<Button>` so as not to use `<Link>` from next.js in cases where it's not needed and was breaking, and updated all the usage to match
There are also a bunch of associated changes in `yarn.lock` and `package-lock.json` - I think this project prefers yarn over npm but I made sure both were up to date
=> Update next.js to 9.4.4, with the necessary fixes

source/app/components/Button/Button.js, source/app/components/DocumentPreview/DocumentPreview.js, source/app/components/TableDownloader/TableDownloader.js, source/app/pages/_app.js, source/package-lock.json, source/package.json, source/yarn.lock
Same as #60, but against kendraMaster
*Issue #, if available:* Relates to #30
* Updated version of next.js to 9.4.4
* Removed the `<Container>` wrapper in _app.js since it's now redundant
* Removed some now-unnecessary module resolution rules that broke in 9.0
* Rearranged the various options available to `<Button>` so as not to use `<Link>` from next.js in cases where it's not needed and was breaking, and updated all the usage to match
There are also a bunch of associated changes in `yarn.lock` and `package-lock.json` - I think this project prefers yarn over npm but I made sure both were up to date
=> Update next.js to 9.4.4, Kendra version

source/app/components/DocumentPreview/DocumentPreview.js, source/app/store/entities/documents/actions.js, source/lambda/jobresultprocessor/lambda_function.py, source/lambda/syncprocessor/lambda_function.py
Kendra was not able to search through images at the moment since we were not indexing their searchable pdfs. 
1. change the name of output document from searchable-pdf.pdf to filenameWithoutExtension-searchable.pdf
2. Indexed the searchable image and pdf files in kendra
=> Index searchable documents (images and pdfs) in kendra

source/package-lock.json, source/package.json, source/yarn.lock
Update elliptic to 6.5.3 and update lodash version to 4.17.19 in package-lock.json and yarn.lock. Fixing other vulnerabilities detected by npm as well
=> Update elliptic to 6.5.3, lodash version to 4.17.19 and other vulnerabilities 

source/package-lock.json, source/package.json, source/yarn.lock
1. Updated elliptic to 6.5.3
2. lodash to 4.17.19 in package-lock.json and yarn.lock
3. Also fixed other vulnerabilities detected by npm
=> Update elliptic to 6.5.3,lodash version to 4.17.19 and other vulnerabilities

source/lambda/helper/python/comprehendHelper.py, source/lib/cdk-textract-stack.ts
a high failure rate in the bulk processing of PDF and PNG
The bulk processor was feeding documents into DUS at a rate beyond its current capacity.  This was causing timeouts and also rate limit exceeded from services, especially ComprehendMedical which doesn't have currently a call "batching" feature.  At present, 2 calls per page need to be made to ComprehendMedical.  Rate limits are handled by retrying with an exponential backoff. 
=> Bulk throttle

README.md, source/bin/run-tests.sh, source/package.json, source/test/test_datastore.py, source/test/test_helper.py
1. Adding tests for the s3helper, dynamodbhelper and Datastore classes.
=> Add unit tests for helper and datastore classes

source/app/store/entities/tracks/data.js
The Classic DUS mode had mentions about Kendra. Fixed the text to remove mention about Kendra for classic mode and for DUS with Kendra mode, added text about Amazon Elasticsearch.
=> Fix the UI pop up text for classic DUS and DUS with kendra modes

source/lambda/apiprocessor/search.py, source/lambda/elasticsearch/requirements.txt, source/lambda/textractor/python/og.py, source/lib/cdk-textract-stack.ts
elasticsearch version upgrade needed for security and approval.
The new ES version and its python client have a different api specification.  Our use needed to be modified in order to create the index, index and delete documents, and search.  
=> elasticsearch upgrade from 6.5 to 7.4

source/package-lock.json, source/package.json, source/yarn.lock
Updated node-fetch to 2.6.1 in package-lock.json and yarn.lock. Tested the changes using both dev deploy and cicd deploy.
=> Upgrade node-fetch to 2.6.1

source/app/store/entities/documents/actions.js, source/app/store/entities/searchResults/actions.js, source/lib/cdk-textract-stack.ts
*Issue #, if available:* N/A
This switches the API Gateway authorizer from the existing Cognito authorizer to IAM - since all the necessary sigv4 request signing is handled internally by Amplify's API handler. This should open the possibility for adding an independent unauthorized role to the identity pool in the future.
=> Switch to use IAM authorizationtype in API

source/lambda/helper/python/comprehendHelper.py, source/lambda/textractor/python/og.py
1. Added a check for entitiesToIndex, if it is empty, we do not process it to extract the items/keywords in it - will occur in case of a blank page
2. Comprehend/Comprehend Medical need atleast 1 character for the detect_entities and other API calls. We initialized rawPages with empty string without any chracters and this gave error for scenarios where the page does not have any text. Fixed this by initializing rawPages with a "." character so that comprehend does not error out.
=> Changes to fix the error of blank page processing in DUS

deployment/install_packages.sh
If the user has previously built DUS and tries to deploy again with some packages in requirements.txt being updated (without deleting the previously built .zip files), the .zip files were not being updated. Adding the code to check if the files are already present, delete them and create new ones again.
=> Update the script to delete .zip files and create new ones if already present

source/lambda/jobresultprocessor/lambda_function.py, source/lambda/syncprocessor/lambda_function.py
Some pdfs were causing an error to be thrown from the lambda jobresultprocessor.
A add() method was erroneously being invoked on a python list,  this was replaced with a append()
=> replaced add() call on list to append()

source/lib/cdk-textract-stack.ts
Add user Pool id to cloudformation stack output to help collect cognito metrics.
=> Add user Pool id to cloudformation stack output

source/app/components/EntitiesCheckbox/EntitiesCheckbox.js, source/app/pages/documents/view.js, source/app/store/entities/documents/actions.js, source/app/utils/document.js, source/app/utils/dus-constants.js, source/app/utils/redaction.js, source/lambda/apiprocessor/redaction.py, source/lambda/boto3/requirements.txt, source/lambda/helper/python/comprehendHelper.py, source/lib/cdk-textract-stack.ts
Implementation of the new Comprehend Pii entities features.  A new tab is offered on the DUS console to see the pii entities and optionally redact them.  Changes are included for the general redaction feature to make the redaction "label" key in a redacted item optional.   An upgrade to boto3 1.17 was necessary in order to have access to the newer PII Comprehend api.
=> Pii entities, redacted item label optional and boto3 upgrade to 1.17

CHANGELOG.md, source/lambda/elasticsearch/requirements.txt, source/package-lock.json, source/package.json, source/yarn.lock
v1.0.14
- Updated certifi and other dependencies 
=> upgrade to version 1.0.14
