aws-solutions/document-understanding-solution

.gitignore
app/components/SearchResults/SearchResults.js
lambda/apiprocessor/search.py

*Issue 5 :* Slow search experience
*Improving customer's search experience: Changes include:*
- *Case-insensitive keyword searches now available*
- *Leveraging Highlight feature in the ES Search API to provide quicker search results*
**Note:** *Instead of the exact word match per document that was available with the search results, the UI would display an approximate word match count at the document level*

Added ES highlight and case-insensitive search

---

deployment/custom-deployment/lib/cdk-textract-stack.ts
lambda/documentprocessor/lambda_function.py
lambda/joberrorhandler/lambda_function.py

This change creates a job error handling process for each document.
When the file is uploaded, a timeout is set for the sync and async jobs for 5 mins and 30 mins respectively. If the document processing has not been completed by then, the errorHandler lambda updates the status as FAILED
*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

Added Lambda,SQS for Basic Error Handling

---

app/components/DocumentList/DocumentList.js
app/components/DocumentListItem/DocumentListItem.js
app/components/DocumentListItem/DocumentListItem.scss
app/pages/documents/index.js
deployment/custom-deployment/lib/cdk-textract-stack.ts

Changes to the errorHandler component
* Changed UI so that failed documents are shown differently on the UI
* Changed Lambda timeout to match SQS visibilty timeout

Fixing SQStimeout and changing UI representation

---

lambda/apiprocessor/search.py
lambda/helper/python/comprehendHelper.py
lambda/jobresultprocessor/lambda_function.py
lambda/syncprocessor/lambda_function.py
lambda/textractor/python/og.py

Description of changes:
1. Indexed the documents using Comprehend Entities
2. Modified the search function. Search can be now performed for keywords as well as for specific key value pairs eg. person:'firstname lastname' etc.
3. Modified the way in which dates in the document are indexed so as to enable search for a date.

Add Advance Search functionality

---

README.md

Updating README regarding Usage and License

Updating README regarding Usage and License

---

source/lambda/asyncprocessor/lambda_function.py
source/lambda/helper/python/comprehendHelper.py
source/lambda/jobresultprocessor/lambda_function.py
source/lambda/syncprocessor/lambda_function.py
source/lambda/textractor/python/og.py

1. Indexed Comprehend Medical entities
2. Indexed Key value pairs from textract
3. Removed repititive imports

Add entities to search:

---

source/lambda/jobresultprocessor/lambda_function.py
source/lambda/syncprocessor/lambda_function.py
source/lambda/textractor/python/og.py

1. Some lines in the PR got messed while rebasing. This commit fixes those lines.

Fix the errors in previous PR  due to merge conflicts

---

deployment/document-understanding-solution.template

Input validation is required on user inputs
Added regex validation of email input to CICD template.

added input validation to email

---

source/lib/cdk-textract-stack.ts

Added AdvancedSecurityMode, added password requirements.

added advanced security mode and password constraints to cognito

---

README.md

Correct a 'architecture' typo.

Correct typo in README.

---

README.md

CICD Deployment is more catered towards deploying the solution via AWS Solutions
Switching Dev Deployment as the initial method for deployment for DUS.

Readme update for deployment methods

---

README.md

Some users have been trying to deploy the solution on their local computers and have faced issues while trying non-Unix based Operating Systems. Adding in a note and recommendation for using Cloud9 for deployments

Update/readme : Cloud9 recommendation for deployments

---

source/lib/cdk-textract-stack.ts

added the 2 endpoints needed for the frontend to perform searches with kendra and also submit feedback to kendra results

added api gateway endpoints for kendra

---

deployment/document-understanding-solution.template

added comments for star resources

---

source/package.json

*Description of changes:* By default, we want to disable the RO mode. The flag was accidentally set to true in the previous commit.

disable the isROMode option

---

source/app/components/Modal/Modal.js
source/app/components/Modal/Modal.scss

- the financial and medical docs no longer appear on top of the modal

Fix the modal error for read only mode 

---

source/package-lock.json
source/package.json
source/yarn.lock

Update lodash to fix the security issue.
Upgrade lodash from 4.17.15 to 4.17.19.

Update lodash to 4.17.19

---

source/lib/cdk-textract-stack.ts

The error page handles the refresh XML error and redirects to home page.

Added an error page to cloudfront distribution

---

README.md

Updates to README instructions with updated deploy information

Updating README instructions

---

source/lambda/customResourceKendraDataSource/lambda_function.py
source/lambda/documentbulkprocessor/lambda_function.py
source/lambda/helper/python/kendraHelper.py
source/lambda/jobresultprocessor/lambda_function.py
source/lambda/syncprocessor/lambda_function.py
source/lib/cdk-textract-stack.ts

bulk processing feature
removed Kendra datasource creation and synch. implemented s3 bulk ingestion bucket lambda processor.

Bulk processing

---

README.md
source/lib/cdk-textract-stack.ts
source/package.json

* Updated Readme and Lambda concurrency
- Added in changes to avoid throttling
- Added explanation for kendra mode
- Added explanation for bulk processing
- Temporarily removed mention of CICD deploy due to existing bug

Minor updates

---

source/app/components/Header/Header.js
source/app/components/Highlight/Highlight.scss
source/app/components/KendraFAQs/KendraFAQs.scss
source/app/components/KendraResultPage/KendraResultPage.js
source/app/components/KendraResultPage/KendraResultPage.scss
source/app/components/KendraTopResults/KendraTopResults.scss
source/app/components/PersonaInfoModal/PersonaInfoModal.js
source/app/components/PersonaInfoModal/PersonaInfoModal.scss
source/app/components/PersonaLabel/PersonaLabel.js
source/app/components/PersonaLabel/PersonaLabel.scss
source/app/components/SearchBar/SearchBar.js
source/app/components/SearchBar/SearchBar.scss
source/app/components/SearchResults/SearchResults.js
source/app/components/SearchResults/SearchResults.scss
source/app/components/SearchTypeTabs/SearchTypeTabs.scss
source/app/pages/documents/documents.scss

* Clicking "document list" now reliably clears the search term
* Fixed alignment and styles within Kendra search result titles
* Rearranged persona selection to remove the option to submit without
using one of the preselected queries
* Added dropdown to easily switch search persona from results
* Persona selection is now cleared when starting a new search
* Layering fixes
* Improved highlighting of multi-word terms in ES results
* Sticky header (search bar + tabs) in search results
* Updated colour on document count text

Further frontend refinements

---

source/package.json

Set the default for enableKendra option to false since we do not want customers to incur more charges unnecessarily .

Set the default for kendra option to false

---

deployment/logger/package-lock.json
deployment/logger/package.json

Changes include dependency upgrades for CICD

Cicd upgrade dependency

---

source/app/components/Header/Header.js
source/app/components/Header/Header.scss
source/app/components/LinkWithClickHandler/LinkWithClickHandler.js
source/app/pages/documents/documents.scss
source/app/pages/home.scss

*Issue #, if available:* N/A
This included a few various fixes for issues seen on mobile layouts
* Home screen flexbox issues only seen in Safari
* Gaps between sticky headers in the document view
* Mobile menu in header

Various mobile responsive issues

---

.viperlightignore
buildspec.yml
deployment/build-open-source-dist.sh
deployment/build-s3-dist.sh

Open source build systems for the Solutions release has to be added
Added CodeBuild buildspec and open source build script for Solutions pipeline.

Open source dist

---

deployment/custom-deployment/bin/add_es_service_role_if_missing.sh
deployment/custom-deployment/bin/update-es-logs-and-client-stack-vars.sh
deployment/document-understanding-cicd/index.js
source/app/components/SearchResults/SearchResults.js
source/app/components/SearchTypeTabs/SearchTypeTabs.js
source/lib/cdk-textract-stack.ts

Refactoring use of Elasticsearch keyword on the UI with Amazon Elasticsearch or Amazon ES

Refactor use of Elasticsearch with Amazon Elasticsearch/ES

---

source/lambda/apiprocessor/document.py
source/lambda/apiprocessor/documents.py
source/lambda/apiprocessor/lambda_function.py
source/lambda/apiprocessor/redact.py
source/lambda/asyncprocessor/lambda_function.py
source/lambda/customResourceKendraDataSource/lambda_function.py
source/lambda/customResourceKendraIndex/lambda_function.py
source/lambda/documentbulkprocessor/lambda_function.py
source/lambda/documentprocessor/lambda_function.py
source/lambda/helper/python/comprehendHelper.py
source/lambda/helper/python/datastore.py
source/lambda/helper/python/helper.py
source/lambda/helper/python/kendraHelper.py
source/lambda/jobresultprocessor/lambda_function.py
source/lambda/kendraIndexPoller/lambda_function.py
source/lambda/syncprocessor/lambda_function.py
source/lambda/textractor/python/og.py
source/lambda/textractor/python/trp.py

Updating logs/print statements for
- Better formatting for log statements
- Removing logging of data (potentially sensitive)
- Adding more information in log statements

Removing unnecessary logs for DUS

---

README.md
source/app/components/FileUpload/FileUpload.js

Added client-side validation checks for
- Supported file types 
- Supported file size limits

Adding basic client-side input validations 

---

deployment/build-open-source-dist.sh
deployment/build-s3-dist.sh

Relevant for AWS open sourcing
Changed paths in open source build script, removed unnecessary files from open source package

updated build paths and remove instructions

---

source/app/store/entities/tracks/data.js

Update compliance track description based on if comprehend medical is enabled or not

Compliance track description update

---

source/app/components/FileUpload/FileUpload.js

We now wait until all documents have been successfully uploaded before rendering the continue button. The main issue was that the upload function was not actually returning an array of promises for us to halt execution using.

wait until docs are uploaded before showing continue button

---

source/app/components/DocumentViewer/DocumentViewer.js
source/app/pages/documents/view.js

Make redaction only take place on compliance track

---

CHANGELOG.md

Update changelog for 2.0.0 release

---

source/yarn.lock

Update elliptic to 6.5.4

---

CHANGELOG.md

Add elliptic update to 1.1.0 changelog

---

CHANGELOG.md
CONTRIBUTING.md
deployment/document-understanding-cicd/index.js
deployment/document-understanding-solution.template
source/package.json

Bump version/1.1.0 + Rename master to main

---

source/app/utils/redaction.js

Make redaction DTO page numbers type Number

---

CHANGELOG.md
source/license-report.txt
source/package-lock.json
source/yarn.lock

updates the json5 package to version 1.0.2 to fix dependabot vulnerability

update json5 version to fix vulnerability

---

CHANGELOG.md
source/license-report.txt
source/package-lock.json
source/yarn.lock

*Description of changes:* Nodejs library updates

update for release v1.0.8

---

README.md

Updating Readme with Deprecation Notice.

Update README.md with Deprecation Notice

---

deployment/logger/package-lock.json
source/package-lock.json
source/yarn.lock

Patching a few Critical and High vulnerabilities

Patching vulnerabilities
